### ISSUE TITLE
Instance Video Cannot be Correctly Detected by the Algorithm

### ISSUE THREAD

**Issue by Roxy-god** [JEOresearch/EyeTracker#1]
I am encountering an issue where the provided instance video within this project is not being correctly processed by the algorithm. Specifically, the algorithm fails to accurately locate the pupil in several frames of the video. Here is the picture of the problem.
<img width="480" alt="联想截图_20240823180159" src="https://github.com/user-attachments/assets/ddf92b42-ab59-407d-a8a7-04fb683ae444">

<img width="480" alt="联想截图_20240823180232" src="https://github.com/user-attachments/assets/2ba069f7-5eb5-4dfb-816b-118133e1252d">
<img width="648" alt="联想截图_20240823180407" src="https://github.com/user-attachments/assets/09dec68b-e6c9-454d-bf61-dafd6a306dc8">

**Comment by willwuwy** [comment]
I met the same issue as well, both on video and webcam stream. However, I tried the initial codes, the issue is still there. I supposed that maybe it was caused by the opencv version? Cuz when I opened debug mode, an error occurred
![image](https://github.com/user-attachments/assets/f489ffc9-ca01-4fb6-9d6a-a266e9fab3c2)

**Comment by willwuwy** [comment]
I found that the darkest point always went wrong, so I tried to change the codes of get_darkest_area. You can try indenting line 72~74. Like this,
![image](https://github.com/user-attachments/assets/35313794-b540-4582-9e49-5a35b4349e1a)
However, the second eye in the test video still has some problems of finding the darkest point, you can try to reduce the value of searchArea, internalSkipSize and min_sum

**Comment by willwuwy** [comment]
BTW, the problem that I met in debug mode, I added a 640*480 white picture to replace "ellipse_reduced_contours",  it always became a list type when a new frame came in.
![image](https://github.com/user-attachments/assets/7480d0ed-0e87-4f3f-8414-266ff11f5629)

**Comment by Mr-Shay** [comment]
@willwuwy 
I fixed this problem by changing this line of code.
<img width="757" alt="e258e559c362307292cc8d93e1aa752" src="https://github.com/user-attachments/assets/8f429611-a0cc-46b4-9b29-6117c0afe5ee">

**Comment by NuncObdurat** [comment]
Thanks all! I updated the main branch with Mr-Shay's fix.
